Add prompt
nim-lang/fusion pull request #19
Opened 2020-09-16 19:02 UTC by juancarlospaco

- Add `prompt` module, 1 proc.
- This is the Nimble terminal "menu thingy" we are using everyday, adapted to work with stdlib.

So more than once been asked "How to import the Nimble menu thingy" or if its possible to do so,
so I tough lets make it happen, and stolen the code from Nimble, is the same code basically.

:)

2020-09-21 02:01 UTC, juancarlospaco commented
Do you prefer other module name?, like `tui` or something?, just in case some day something can be added to it.
:thinking:

2020-10-16 22:33 UTC, timotheecour commented on src/fusion/tui.nim
> +##   echo promptInteractive("is Schrödinger's Cat alive?", ["maybe", "maybe", "maybe"])
* yes no maybe, otherwise not clear it works

2020-10-16 22:37 UTC, timotheecour commented on src/fusion/tui.nim
> +proc promptInteractive*(question: string, answers: openarray[string], width: Positive = 80): string =
can we make sure CI is hardened to fail here (because of openArray vs openarray), eg by adding `--styleCheck:on` to `test` nimble task ?

2020-10-16 22:39 UTC, timotheecour commented on src/fusion/tui.nim
> +## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
tui is a bad name. termutils?

2020-10-17 00:03 UTC, Yardanico reviewed
Some small corrections and simplifications (didn't test)

2020-10-17 00:03 UTC, Yardanico commented on src/fusion/terminalutils.nim
> +      for s in 0..<(arg.len + 4): cursorBackward(stdout)
```suggestion
      stdout.cursorBackward(arg.len + 4)
```

2020-10-17 00:03 UTC, Yardanico commented on src/fusion/terminalutils.nim
> +  ## Terminal prompt that asks a `question` and returns 1 answer from `answers`.
```suggestion
  ## Terminal prompt that asks a `question` and returns only one of the answers from possible `answers`.
```

2020-10-17 00:03 UTC, Yardanico commented on src/fusion/terminalutils.nim
> +  assert question.len > 0, "question must not be empty string"
```suggestion
  assert question.len > 0, "Question must not be empty"
```

2020-10-17 00:06 UTC, Yardanico commented on src/fusion/terminalutils.nim
> +    for i in 0..<answers.len: cursorUp(stdout)
```suggestion
    stdout.cursorUp(answers.len)
```

2020-10-17 00:09 UTC, Yardanico commented on src/fusion/terminalutils.nim
> +## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
Also maybe we should have a more generic top level documentation if this module is named "terminalutils"? And move prompt-specific info into it's own docs

2020-10-17 00:55 UTC, Yardanico commented
This is the version with my small styling/functionality changes just for reference:
```nim
proc promptInteractive*(question: string, answers: openArray[string], width: Positive = 80): string =
  ## Terminal prompt that asks a `question` and returns only one of the answers from possible `answers`.
  ##
  ## .. code-block:: Nim
  ##   echo promptInteractive("is Schrödinger's Cat alive?", ["yes", "no", "maybe"])
  ##
  # Adapted from Nimble source code to stdlib, adding width optional argument.
  assert question.len > 0, "Question must not be empty"
  assert answers.len > 0, "There must be at least one possible answer"
  writeStyled(question, {styleBright})
  var
    current = 0
    selected = false
  # Incase the cursor is at the bottom of the terminal
  for arg in answers: stdout.write "\n"
  # Reset the cursor to the start of the selection prompt
  cursorUp(stdout, answers.len)
  cursorForward(stdout, width)
  hideCursor(stdout)

  # The selection loop
  while not selected:
    setForegroundColor(fgDefault)
    # Loop through the options
    for i, arg in answers:
      # Check if the option is the current
      if i == current:
        writeStyled("> " & arg & " <", {styleBright, styleUnderscore})
      else:
        writeStyled("  " & arg & "  ", {styleDim})
      # Move the cursor back to the start
      cursorBackward(stdout, arg.len + 4)
      # Move down for the next item
      cursorDown(stdout)
    # Move the cursor back up to the start of the selection prompt
    cursorUp(stdout, answers.len)
    resetAttributes(stdout)

    # Ensure that the screen is updated before input
    flushFile(stdout)
    # Begin key input
    while true:
      case getch():
      of '\t', '\x1B':
        current = (current + 1) mod answers.len
        break
      of '\r', ' ':
        selected = true
        break
      of '\3':
        showCursor(stdout)
        raise newException(OSError, "Keyboard interrupt")
      else: discard

  # Erase all lines of the selection
  for i in 0 ..< answers.len:
    eraseLine(stdout)
    cursorDown(stdout)
  # Move the cursor back up to the initial selection line
  cursorUp(stdout, answers.len)
  showCursor(stdout)
  result = answers[current]
```

I've found some problems with the implementation:
1) Default width is IMO too high, it should probably be calculated as a width of the longest answer + length of the question + 2
2) Maybe it's better to put possible answers on the next line? Then we'll have less width usage since the question could be long, but the answers will be short

2020-10-17 01:00 UTC, timotheecour commented
can this be customized to use a horizontal vs vertical layout?

2020-10-17 01:01 UTC, Yardanico commented
@timotheecour you mean questions on a single line vs questions on separate lines?

2020-10-17 01:46 UTC, timotheecour commented
no I mean answers layout

2020-10-19 22:44 UTC, juancarlospaco commented on src/fusion/terminalutils.nim
> +  for i in 0..<answers.len: cursorUp(stdout)
Thanks for the contribution, but all the suggestions are on the latest commit together.

2020-10-19 22:45 UTC, juancarlospaco commented on src/fusion/terminalutils.nim
> +      for s in 0..<(arg.len + 4): cursorBackward(stdout)
Thanks for the contribution, but all the suggestions are on the latest commit together.

2020-10-19 22:45 UTC, juancarlospaco commented on src/fusion/terminalutils.nim
> +    for i in 0..<answers.len: cursorUp(stdout)
Thanks for the contribution, but all the suggestions are on the latest commit together.

2020-10-19 22:46 UTC, juancarlospaco commented on src/fusion/tui.nim
> +proc promptInteractive*(question: string, answers: openarray[string], width: Positive = 80): string =
Out of scope for this PR, but I like the idea.

2020-10-20 00:20 UTC, timotheecour commented on src/fusion/terminalutils.nim
> +  assert question.len > 0, "Question must not be empty"
I know https://github.com/nim-lang/RFCs/issues/266 is still in RFC mode, but this should use `enforce`, it's a recoverable exception and validates user input, not internal logic that should crash the application.

2020-10-20 20:18 UTC, TensorTom commented
Was mentioned [here](https://forum.nim-lang.org/t/6965#43620).

2020-10-20 21:03 UTC, alaviss requested changes
Since this was ripped off nimble code, please insert the corresponding copyright and license for the file.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2

The license from https://github.com/nim-lang/nimble/blob/master/license.txt should be inlined into this file header and not `license.txt` as fusion is not dual-licensed.

2020-10-20 22:15 UTC, timotheecour commented on src/fusion/terminalutils.nim
>  ## * Utilities and convenience procs built on top of `terminal` module.
* add `Adapted from: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2` so we can trace it back to its origin (say in case a refactor between the 2 is later done, or bugfixes are done in either)
* @alaviss just wondering if it's ok to have a license file as here; a package that imports (recursively) terminalutils may not be aware that one of its dependencies is subject to this license?

2020-10-20 22:29 UTC, alaviss commented on src/fusion/terminalutils.nim
> +## `Nimble source code <https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2>`_
```suggestion
## `Nimble source code <https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim>`_
```

2020-10-20 22:29 UTC, alaviss commented on src/fusion/terminalutils.nim
>  ## * Utilities and convenience procs built on top of `terminal` module.
> @alaviss just wondering if it's ok to have a license file as here; a package that imports (recursively) terminalutils may not be aware that one of its dependencies is subject to this license?

It should be fine, BSD 3-clause is compatible with MIT AFAIK. Also the mix-and-match of licenses within a project is not unusual and people who have strict legality requirements must subject themselves to audit every single dependency used.

2020-11-06 17:32 UTC, juancarlospaco commented
Ready to merge.

2020-11-06 17:49 UTC, timotheecour commented
@juancarlospaco can you assign the review to @dom96 instead because of the code history?

2020-11-06 17:56 UTC, juancarlospaco commented
@timotheecour 
I do not have permission to do it.

2020-11-06 18:04 UTC, timotheecour commented
done

2020-11-07 12:36 UTC, dom96 commented
> So more than once been asked "How to import the Nimble menu thingy" or if its possible to do so,
so I tough lets make it happen, and stolen the code from Nimble, is the same code basically,
code is already there anyways..., just making it more usable.

There is a reason the Nimble code is available as a library, why not just use it?

2020-11-07 15:39 UTC, nc-x commented
Firstly, I would like to say that i am one of the few people who still do not understand the reasoning behind fusion, and the criteria by which a module is supposed to be put into stdlib, or fusion, or a separate nimble package.
  
Personally, I would have preferred no fusion, and some of the modules from here should have been in stdlib and some as separate nimble packages, so I won't comment on whether we need this terminalutils in fusion or not.

However,
> There is a reason the Nimble code is available as a library, why not just use it?

(I don't know how much code is included in the nimble as a library, so i may be wrong but anyways...)
  
Because nimble is not a tui library? And if I need simple tui utilities I would prefer importing a simple stdlib module, or a tui library from nimble, and not import a fullblown package manager just to use 5% of its functionality, especially considering the fact that the functionality I want to use has nothing to do with package management?

2020-11-07 16:05 UTC, dom96 commented
@nc-x nothing stops you from just importing the ``cli`` module from Nimble. Just ``import nimblepkg/cli`` and you can use it. It's a pretty lightweight module: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim

2020-11-07 16:14 UTC, nc-x commented
Is the cli module a separate nimble package, or does it come inside the nimble package?

the download size of nimble won't be particularly big, but still (atleast to me) it doesn't feel right to add dependency to nimble.

In any case, we also need to take into account the discoverability of nimble as a tui library. Even if nimble directory shows nimble when searching for tui library, most people are going to ignore it thinking that maybe it is tagged wrong because nimble is a package manager not tui library.

2020-11-07 18:16 UTC, timotheecour commented
> it doesn't feel right to add dependency to nimble for using tui utilities

I agree. And even though nimble is, well, a package, manager, it would still be possible for it to have a `require tui` optional dependency (not sure if feasible at the moment, but it's doable). Libraries grow and having a dedicated `tui` package makes more sense than having to rely on nimble, as it'd quickly enter a friction mode (separation of concerns: nimble shouldn't focus on full blown tui). So I support having `tui` separately from nimble instead of requiring a dependency on nimble.


> one of the few people who still do not understand the reasoning behind fusion, and the criteria by which a module is supposed to be put into stdlib, or fusion, or a separate nimble package

you are not alone; for me it's still very much an experiment, and some downsides are as follows:
* requiring it to work with nim all the way down to 1.0.x may add too much friction
* slower development pace compared to individual nimble package; in particular, the fact there's no "staging period" (combined with lack of semver, refs https://github.com/nim-lang/fusion/issues/30) is a flaw; it means you can't have trial/error phase that is essential for maturing libraries, especially in between point releases
* the fact that fusion is be bundled with nim (even copied into std during install) means you'll end up with duplicate fusion imports: one from the bundled fusion, and one from pkg/fusion; this in particular will lead to duplicate symbol link errors as soon as you have some exportc symbols defined; see the whole thread here: https://github.com/nim-lang/fusion/issues/25#issuecomment-708099682 that worries me a lot

on the flip side, the positive aspects about fusion would be:
* community maintained (no package-gone-rogue/unmaintained)
* batteries included extended standard library, where things work well together
* common infrastructure to reduce overhead (testing/docs/etc) + more visibility

2020-11-07 22:16 UTC, dom96 commented
> Is the cli module a separate nimble package, or does it come inside the nimble package?

Yeah, it's part of the `nimble` package. To be fair, now that Nimble supports multiple packages in the same repo, exposing the ``cli`` module as another package should be very trivial. I would prefer to see that as a PR rather than this :)

2020-11-20 13:18 UTC, closed without merging