Add division by zero, fixes DivByZeroError
nim-lang/fusion pull request #64
Opened 2021-01-03 15:52 UTC by juancarlospaco

WIP

2021-01-03 19:29 UTC, timotheecour commented on .github/workflows/ci.yml
> +          nimble --styleCheck:hint test
update existing `tests/config.nims` instead; it's more flexible

2021-01-03 19:32 UTC, juancarlospaco commented on .github/workflows/ci.yml
> +          nimble --styleCheck:hint test
WIP, I was testing, theres stuff on Nim main repo on `std/private/*` that has broken style.

2021-01-03 19:32 UTC, timotheecour commented on .github/workflows/ci.yml
> +          key: ${{ runner.os }}-${{ runner.cpu }}-choosenim-${{ matrix.branch }}
can branch = devel  be cached? (idk, I'm just asking)

2021-01-03 19:35 UTC, timotheecour commented on tests/tmatching.nim
> +    # main()  # Error: cannot generate code; too many registers required
I know it's a WIP, but how come did CI pass before but not here without this?

2021-01-03 19:35 UTC, juancarlospaco commented on .github/workflows/ci.yml
> +          key: ${{ runner.os }}-${{ runner.cpu }}-choosenim-${{ matrix.branch }}
`${{ matrix.branch }}` is `devel` branch, and also `1.4` and `1.2`, from the matrix.

2021-01-03 19:38 UTC, timotheecour commented on src/fusion/docutils.nim
> +  docComand = " doc -r --project --docroot --outdir:htmldocs --styleCheck:hint -" # nim doc command part that never changes
`-r` would open html in a browser, doesn't seem to make sense in CI?

2021-01-03 19:44 UTC, timotheecour commented on src/fusion/docutils.nim
> +  let ret = execCmdEx(nim & ' ' & extra & docComand, input = code)
* the previous way with `fmt` was more readable IMO
* extra must be after docCommand anyways so it can override flags in docCommand

2021-01-03 19:45 UTC, timotheecour commented on src/fusion/docutils.nim
> +  docComand = " doc -r --project --docroot --outdir:htmldocs --styleCheck:hint -" # nim doc command part that never changes
if `--styleCheck:error` works, even better?

2021-01-03 19:47 UTC, timotheecour commented on src/fusion/docutils.nim
> +      if name[0] == 'j' and name[1] == 's':
`if name.startsWith "js"` is more readable / searchable.
(Efficiency doesn't matter here, the rest of the code dwarfs whatever difference this would make)
(if needed add import strutils)

2021-01-03 20:01 UTC, timotheecour commented
@juancarlospaco how about this:
in fusion.nimble:
```
  exec "nim c -r src/fusion/docutils " & srcDir
=>
  exec "nim c -r src/fusion/docutils " & srcDir & " --outdir:htmldocs_js -d:fusionJsDocs"
  exec "nim c -r src/fusion/docutils " & srcDir & " --outdir:htmldocs"
```
and then handle `when defined(fusionJsDocs)` properly in docutils.nim

=> then we end up with 2 top-level dirs for docs:
a js-only one
a regular backend-only one

2021-01-03 20:50 UTC, timotheecour commented on tests/tmatching.nim
> +              # Fails on 1.0.0 only.
`when (NimMajor, NimMinor, NimPatch)` ...

why did it work before PR?

(curious whether it got fixed by https://github.com/nim-lang/Nim/pull/15705)

for reference (CI logs eventually expire):
```
/home/runner/work/fusion/fusion/fusion/tests/tmatching.nim(165, 9) template/generic instantiation of `main` from here
/home/runner/work/fusion/fusion/fusion/src/fusion/matching.nim(2101, 21) Error: cannot generate code; too many registers required
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "/home/runner/.nimble/bin/nim" c --noNimblePath -d:NimblePkgVersion=1.0 "-r" "--path:."  "/home/runner/work/fusion/fusion/fusion/tests/tmatching"
Error: Process completed with exit code 1.
```

2021-01-03 21:00 UTC, timotheecour commented on fusion.nimble
> +  exec "nim c -r src/fusion/docutils " & srcDir & " --outdir:htmldocs_js -d:js"
`-d:js` sounds fragile because it's set by the backend and can confuse code that uses when defined(c), when defined(js) etc.

instead, would `-b:js` work (but might not work for earlier versions of nim), or `-d:fusionDocJs` which can then be handled by docutils ?

2021-01-03 21:19 UTC, timotheecour commented on tests/tmatching.nim
> +    when (NimMajor, NimMinor, NimPatch) > (1, 4, 2):
`when (NimMajor, NimMinor, NimPatch) > (x, y, z)` is probably incorrect, you should always use `when (NimMajor, NimMinor, NimPatch) >= (first version where this is fixed)`

because what if `(1,4,4)` is released and it doesn't include the fix?

so I'd use:
`when (NimMajor, NimMinor, NimPatch) >= (1, 5, 1):`  (if that's what you mean here)

ditto above, replace:
when (NimMajor, NimMinor) > (1, 0):
with:
`when (NimMajor, NimMinor) >= (1, 2):`
or 
`when (NimMajor, NimMinor, NimPatch) >= (1, 0, 2):`
whichever is appropriate

2021-01-03 21:43 UTC, timotheecour commented on src/fusion/docutils.nim
> +    when defined(fusionDocJs) and (NimMajor, NimMinor) >= (1, 5): "-b:js "
* but then it'll ignore fusionDocJs for old nim; instead, either support old nim here to actually do the right thing, or (simpler, good enough maybe) just move `(NimMajor, NimMinor) >= (1, 5)` to fusion.nimble:

```nim
when (NimMajor, NimMinor) >= (1, 5):
  exec "nim c -r -d:fusionDocJs src/fusion/docutils " & srcDir & " --outdir:htmldocs_js -d:js -d:fusionDocJs"
```

* also, -b:js was intrdouced in (1,4) IIRC

2021-01-03 22:16 UTC, juancarlospaco commented
`--styleCheck:error ` can not be for now,
because theres stuff with broken style on Nim main repo on `/lib/js/jsffi.nim` and `std/private/*.nim`.

2021-01-03 23:24 UTC, timotheecour commented
> because theres stuff with broken style on Nim main repo on /lib/js/jsffi.nim and /lib/std/private/*.nim.

I see, you're hitting https://github.com/nim-lang/Nim/issues/10201

> theres stuff with broken style on Nim main repo

=> https://github.com/timotheecour/Nim/issues/64#issuecomment-753691214

2021-01-03 23:27 UTC, timotheecour commented on fusion.nimble
>  task docs, "":
running locally `nimble docs` fails:
```
/Users/timothee/git_clone/nim/fusion/src/fusion/docutils.nim(49) docutils
/Users/timothee/git_clone/nim/fusion/src/fusion/docutils.nim(42) genDocs
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(30) failedAssertImpl
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(23) raiseAssert
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/fusion/src/fusion/docutils.nim(42, 14) `false` /Users/timothee/git_clone/nim/Nim_devel/lib/system/jssys.nim(54, 1) Error: redefinition of 'getCurrentException'; previous declaration here: /Users/timothee/git_clone/nim/Nim_devel/lib/system.nim(2386, 8)
```

2021-01-03 23:39 UTC, juancarlospaco commented
Can not reproduce, also works on the CI.

![temp](https://user-images.githubusercontent.com/1189414/103491568-af6da900-4e03-11eb-90e4-0ffee6076754.png)

2021-01-04 05:42 UTC, timotheecour commented
@juancarlospaco 
as i predicted in https://github.com/nim-lang/fusion/pull/64#discussion_r551053905, passing explicitly `-d:js` is incorrect.

reduced case for the error i had in https://github.com/nim-lang/fusion/pull/64#discussion_r551068377 with `nimble docs`:

echo "discard" > z03.nim
XDG_CONFIG_HOME= nim doc -b:js -d:js z03.nim

/Users/timothee/git_clone/nim/Nim_devel/lib/system/jssys.nim(54, 1) Error: redefinition of 'getCurrentException'; previous declaration here: /Users/timothee/git_clone/nim/Nim_devel/lib/system.nim(2386, 8)

devel a0134671eeed3cfac1e9035568cbdec41825da8d: error
1.4.0: no error (might explain why you didn't get an error)

I'm not sure why CI doesn't show an error here (maybe another bug that hides this bug; we should investigate whether fusion CI actually also runs on latest nim devel instead of a cached version or a nightly), but the fix here is:
```
exec "nim c -r -d:fusionDocJs src/fusion/docutils " & srcDir & " -d:js -d:fusionDocJs"
=>
exec "nim c -r -d:fusionDocJs src/fusion/docutils " & srcDir
```

2021-01-04 19:36 UTC, timotheecour approved these changes

2021-01-04 19:44 UTC, timotheecour commented on fusion.nimble
>  task docs, "":
resolved in recent commit

2021-01-04 19:48 UTC, timotheecour requested changes
i don't quite understand the changes in tests/tmatching.nim ; didn't CI pass before your PR ?

also links like `https://github.com/nim-lang/fusion/pull/64/checks?check_run_id=1640671490#step:8:251` expire (CI keeps those for limited time only) so these should point to somewhere else, for example:

* copy paste the relevant part of logs into a conversation comment in this PR (showing the source)
* link to those instead (would look like: https://github.com/nim-lang/fusion/pull/64#issuecomment-753683927)

2021-01-04 20:35 UTC, juancarlospaco commented
I can revert `tests/tmatching.nim` but CI wont be green, you literally passed the code to workaround it. :shrug:

2021-01-04 21:11 UTC, timotheecour commented
> but CI wont be green

but I'm trying to understand why is CI green currently (before your PR) ?

2021-01-04 21:24 UTC, juancarlospaco commented
[You already seen the test that wont pass with specific versions](https://github.com/nim-lang/fusion/pull/64#discussion_r551055696), etc. 
I am just trying to make it more strict, cover JS too, even tried to enforce style.
:)

2021-01-04 21:44 UTC, timotheecour commented
>  feel free to close it.

your PR is good, I'm just trying to understand that specific point; I'll do some experiments in https://github.com/nim-lang/fusion/pull/66 to understand what's going on with tests/tmatching.nim

2021-01-04 23:18 UTC, timotheecour commented
indeed, I was right to be suspicious about the changes to tests/tmatching.nim; see https://github.com/nim-lang/fusion/issues/68 and https://github.com/nim-lang/fusion/pull/67; they shouldn't be needed
(some changes that fix style are ok though)

2021-01-05 21:08 UTC, timotheecour approved these changes

2021-01-08 03:06 UTC, xflywind approved these changes

2021-01-08 15:17 UTC, juancarlospaco commented
@timotheecour ping. Also https://github.com/nim-lang/Nim/pull/16630#issuecomment-756668463

2021-01-08 17:59 UTC, merged